version: 2
updates:
  - package-ecosystem: nuget
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    groups:
      temporal:
        patterns:
          - "Temporalio*"
      microsoft:
        patterns:
          - "Microsoft.*"
          - "Azure.*"
    ignore:
      - dependency-name: "Microsoft.Extensions.*"
        update-types: ["version-update:semver-major"]
      - dependency-name: "Microsoft.AspNetCore.*"
        update-types: ["version-update:semver-major"]
      - dependency-name: "Microsoft.CodeAnalysis.*"
        update-types: ["version-update:semver-major"]
      - dependency-name: "Microsoft.NET.Test.Sdk"
        update-types: ["version-update:semver-major"]
      - dependency-name: "Microsoft.SourceLink.GitHub"
        update-types: ["version-update:semver-major"]
      - dependency-name: "System.*"
        update-types: ["version-update:semver-major"]
    labels:
      - dependencies

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    labels:
      - dependencies
