using System.Text;
using Microsoft.CodeAnalysis;
using Kogoshvili.Temporal.Cli.Analysis;

namespace Kogoshvili.Temporal.Cli.Presets;

/// <summary>
/// Generates an <c>.editorconfig</c> severity block for a named preset from the
/// analyzer's diagnostic descriptors, keeping the descriptors the single source
/// of truth. <c>recommended</c> mirrors today's defaults; <c>strict</c> turns
/// every rule (including opt-in ones) into an error.
/// </summary>
internal static class SeverityPresetGenerator
{
    public const string Recommended = "recommended";
    public const string Strict = "strict";

    public static string Generate(string tier)
    {
        var descriptors = AnalysisRunner.Analyzers
            .SelectMany(a => a.SupportedDiagnostics)
            .GroupBy(d => d.Id, StringComparer.Ordinal)
            .Select(g => g.First())
            .OrderBy(d => d.Id, StringComparer.Ordinal)
            .ToList();

        var sb = new StringBuilder();
        sb.AppendLine($"# Kogoshvili.Temporal severity preset: {tier}");
        sb.AppendLine($"# Generated by `temporal-sharp preset {tier}`. Do not edit by hand.");
        sb.AppendLine();
        sb.AppendLine("[*.cs]");

        foreach (var descriptor in descriptors)
        {
            sb.AppendLine($"dotnet_diagnostic.{descriptor.Id}.severity = {Severity(tier, descriptor)}");
        }

        return sb.ToString().TrimEnd() + "\n";
    }

    private static string Severity(string tier, DiagnosticDescriptor descriptor)
    {
        if (tier == Strict)
        {
            return "error";
        }

        return descriptor.IsEnabledByDefault
            ? descriptor.DefaultSeverity.ToString().ToLowerInvariant()
            : "none";
    }
}
