<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>Kogoshvili.Temporal.AspNetSample</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Temporal.Hosting\Temporal.Hosting.csproj" />
  </ItemGroup>

</Project>
